import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class AdminConstantsService {
  postTypes = [
    { value: 'blog' },
    { value: 'video' },
    { value: 'podcast' },
    { value: 'community' },
    { value: 'release' },
  ];

  urlMatches = [
    // *****  VIDEOS  *****
    {
      matchSubstring: 'https://www.youtube.com/watch?',
      postFormPatch: {
        type: 'video',
        sourceSite: 'YouTube',
        sourceUrl: 'https://youtube.com',
      },
    },
    {
      matchSubstring: 'https://youtu.be',
      postFormPatch: {
        type: 'video',
        sourceSite: 'YouTube',
        sourceUrl: 'https://youtube.com',
      },
    },
    // *****  BLOGS  *****
    {
      matchSubstring: 'https://dev.to/',
      postFormPatch: {
        type: 'blog',
        sourceSite: 'DEV Community',
        sourceUrl: 'https://dev.to',
      },
    },
    {
      matchSubstring: 'medium.com/',
      postFormPatch: {
        type: 'blog',
        sourceSite: 'Medium',
        sourceUrl: 'https://medium.com',
      },
    },
    {
      matchSubstring: 'hashnode.dev/',
      postFormPatch: {
        type: 'blog',
        sourceSite: 'Hashnode',
        sourceUrl: 'https://hashnode.com',
      },
    },
    {
      matchSubstring: 'https://blog.angular.io',
      postFormPatch: {
        type: 'blog',
        sourceSite: 'Angular Blog',
        sourceUrl: 'https://blog.angular.io',
      },
    },
    {
      matchSubstring: 'https://www.telerik.com/blogs',
      postFormPatch: {
        type: 'blog',
        sourceSite: 'Telerik Blogs',
        sourceUrl: 'https://www.telerik.com/blogs',
      },
    },
    // *****  PODCASTS  *****
    {
      matchSubstring: 'https://topenddevs.com/',
      postFormPatch: {
        type: 'podcast',
        sourceSite: 'DevChat.tv',
        sourceUrl: 'https://adventuresinangular.com',
        authorName: 'Adventures In Angular',
        authorUrl: 'https://topenddevs.com/podcasts/adventures-in-angular/',
      },
    },
    {
      matchSubstring: 'https://www.spreaker.com/user/ng-conf',
      postFormPatch: {
        type: 'podcast',
        sourceSite: 'Spreaker',
        sourceUrl: 'https://www.spreaker.com',
        authorName: 'The Angular Plus Show',
        authorUrl: 'https://www.spreaker.com/show/angular-show',
      },
    },
    {
      matchSubstring: 'https://www.spreaker.com/user/14532324/',
      postFormPatch: {
        type: 'podcast',
        sourceSite: 'Spreaker',
        sourceUrl: 'https://spreaker.com',
        authorName: 'Angular Experience',
        authorUrl: 'https://angular-experience.web.app/episodes',
      },
    },
    {
      matchSubstring: 'https://open.spotify.com',
      postFormPatch: {
        type: 'podcast',
        sourceSite: 'Spotify',
        sourceUrl: 'https://open.spotify.com',
        authorName: 'Angular Master Podcast',
        authorUrl: 'https://open.spotify.com/show/1wgZAEEIoRZ8eP78LTbyZf',
      },
    },
    {
      matchSubstring: 'https://webrush.io/episodes/',
      postFormPatch: {
        type: 'podcast',
        sourceSite: 'WebRush',
        sourceUrl: 'https://webrush.io',
      },
    },
    // *****  RELEASES  *****
    {
      matchSubstring: 'https://github.com/angular/angular/releases',
      postFormPatch: {
        type: 'release',
        sourceSite: 'GitHub Angular Releases',
        sourceUrl: 'https://github.com/angular/angular/releases',
      },
    },
  ];

  allTags = [
    '@Attribute',
    '@ContentChild',
    '@HostBinding',
    '@HostListener',
    '@Input',
    '@Inject',
    '@Injectable',
    '@Optional',
    '@Output',
    '@Skip',
    '@SkipSelf',
    '@ViewChild',
    '@ViewChildren',
    '*ngFor',
    '*ngIf',
    '*ngSwitch',
    ':host',
    ':host-context',
    '::ng-deep',
    '<ng-container>',
    '<ng-content>',
    '<ng-template>',
    '<router-outlet>',
    'Accessibility',
    'ActivatedRoute',
    'ActivatedRouteSnapshot',
    'Angular Elements',
    'Angular Universal',
    'Animations',
    'Architecture',
    'APP_INITIALIZER',
    'Attribute Binding',
    'Builders',
    'CanActivate',
    'CanActivateChild',
    'CanDeactivate',
    'CanLoad',
    'CanMatch',
    'CLI',
    'Change Detection',
    'ChangeDetectorRef',
    'Class Binding',
    'Components',
    'Component Factory',
    'Content Projection',
    'ControlContainer',
    'ControlValueAccessor',
    'Data Binding',
    'Data Transfer',
    'Event Binding',
    'Debugging',
    'Decorators',
    'Dependency Injection',
    'Deployment',
    'Directives',
    'ElementRef',
    'ENVIRONMENT_INITIALIZER',
    'Environments',
    'EventEmitter',
    'ExpressionChangedAfterItHasBeenCheckedError',
    'Extended Diagnostics',
    'FormBuilder',
    'FormArray',
    'FormControl',
    'FormGroup',
    'Forms',
    'HttpClient',
    'HttpContext',
    'HttpInterceptors',
    'HttpParams',
    'Hot Module Replacement',
    'InjectionToken',
    'Internationalization',
    'Interpolation',
    'Ivy',
    'Lazy Loading',
    'Libraries',
    'Lifecycle Hooks',
    'Modules',
    'NavigationCancel',
    'NavigationCancellationCode',
    'NgZone',
    'One-Way Data Binding',
    'OnPush',
    'Optional Modules',
    'ParamMap',
    'PWA',
    'Performance',
    'Pipes',
    'Preloading',
    'Property Binding',
    'Query Params',
    'QueryList',
    'Reactive Forms',
    'Resolve',
    'Route Guards',
    'Route Params',
    'RouteReuseStrategy',
    'Routing',
    'SPA',
    'Schematics',
    'Services',
    'Standalone Components',
    'Style Binding',
    'Template Reference Variable',
    'Template Driven Forms',
    'TemplateRef',
    'TestBed',
    'Title',
    'Two-Way Data Binding',
    'Typed Forms',
    'Update',
    'Validation',
    'ViewContainerRef',
    'ViewEncapsulation',
    'createComponent()',
    'createEmbeddedView()',
    'detectChanges()',
    'getTitle()',
    'inject()',
    'let-*',
    'markForCheck()',
    'ng build',
    'ng completion',
    'ng serve',
    'ng test',
    'ngAfterContentChecked()',
    'ngAfterContentInit()',
    'ngAfterViewChecked()',
    'ngAfterViewInit()',
    'ngComponentOutlet',
    'ngDoCheck()',
    'ngModel',
    'ngOnChanges()',
    'ngOnDestroy()',
    'ngOnInit()',
    'ngPlural',
    'ngPluralCase',
    'ngTemplateOutlet',
    'ngTemplateOutletContext',
    'ngTemplateOutletInjector',
    'patchValue()',
    'routerLink',
    'routerLinkActive',
    'runInContext',
    'setTitle()',
    'setValue()',
    'trackBy',
    'useClass',
    'useExisting',
    'useFactory',
    'useValue',
    'Auth',
    'Autocomplete',
    'Bash Scripts',
    'BreakpointObserver',
    'Bundle Size',
    'Caching',
    'Charts',
    'CI/CD',
    'CORS',
    'Community',
    'Configuration',
    'Cookies',
    'CRUD',
    'CSRF',
    'Custom',
    'DOM Manipulation',
    'Design Patterns',
    'Destructuring',
    'Domain Driven Design',
    'Dot Files',
    'Dynamic',
    'ESLint',
    'Errors',
    'Facade Design Pattern',
    'Feature Flags',
    'File Upload',
    'Geolocation',
    'IntersectionObserver',
    'JSON',
    'JWT',
    'Linters',
    'localStorage',
    'Maps',
    'Menu',
    'Micro Frontends',
    'Microservices',
    'Mixins',
    'Mobile',
    'Module Federation',
    'Monorepo',
    'PDF',
    'Pagination',
    'Path Mapping',
    'Phone',
    'Productivity',
    'Responsive',
    'Scrolling',
    'SEO',
    'SMS',
    'SSR',
    'Sanitization',
    'Search',
    'Security',
    'Service Workers',
    'Slider',
    'Skeletons',
    'Spinner',
    'State Management',
    'Styles',
    'Webpack',
    'Web Components',
    'Web Workers',
    'XSS',
    'iframe',
    'Assertions',
    'Code Coverage',
    'Cypress',
    'Dummies',
    'Fakes',
    'Jasmine',
    'Jest',
    'Karma',
    'Mocks',
    'Protractor',
    'Stubs',
    'Testing',
    'Unit Testing',
    'E2E Testing',
    'TDD',
    'AST',
    'Async Pipe',
    'Constructor',
    'Enums',
    'Generics',
    'Generators',
    'Getters/Setters',
    'Interfaces',
    'Nullish Coalescing',
    'Promises',
    'Strict Mode',
    'Tagged Union Types',
    'TypeScript',
    'Utility Types',
    'Angular Material',
    'Angular CDK',
    'Button',
    'Checkbox',
    'Chips',
    'cdkTrapFocus',
    'Clipboard',
    'Component Harness',
    'Data Table',
    'Datepicker',
    'Dialog',
    'Drag and Drop',
    'Form Field',
    'Overlay',
    'Portals',
    'Progress',
    'Select',
    'Sidenav',
    'Tabs',
    'Theming',
    'Toolbar',
    'Tooltip',
    'NgRx',
    'Actions',
    'ComponentStore',
    'NgRx Data',
    'Effects',
    'NgRX',
    'Reducers',
    'Selectors',
    'AsyncSubject',
    'BehaviorSubject',
    'Hot vs Cold',
    'Marble Testing',
    'Observables',
    'ReplaySubject',
    'RxJS',
    'Schedulers',
    'Service with a Subject',
    'Subject',
    'Subscriptions',
    'Void Subject',
    'ajax()',
    'bindCallback()',
    'bindNodeCallback()',
    'catchError()',
    'combineLatest()',
    'combineLatestAll()',
    'combineLatestWith()',
    'complete',
    'concat()',
    'concatMap()',
    'concatAll()',
    'count()',
    'debounce()',
    'debounceTime()',
    'defer()',
    'dematerialize()',
    'distinct()',
    'distinctUntilChanged()',
    'exhaustAll()',
    'exhaustMap()',
    'expand()',
    'filter()',
    'finalize()',
    'first()',
    'forkJoin()',
    'from()',
    'fromEvent()',
    'fromEventPattern()',
    'generate()',
    'iif()',
    'interval()',
    'map()',
    'materialize()',
    'mergeAll()',
    'mergeMap()',
    'multicast()',
    'of()',
    'pairwise()',
    'pipe()',
    'pluck()',
    'range()',
    'retry()',
    'retryWhen()',
    'scan()',
    'share()',
    'shareReplay()',
    'startWith()',
    'switchAll()',
    'switchMap()',
    'take()',
    'takeUntil()',
    'tap()',
    'throwError()',
    'timer()',
    'unsubscribe()',
    'withLatestFrom()',
    'zip()',
    'AG Grid',
    'Akita',
    'AngularFire',
    'Auth0',
    'AWS',
    'Azure',
    'Bootstrap',
    'Capacitor',
    'D3',
    'Docker',
    'DevTools',
    'Electron',
    'ExpressJS',
    'Firebase',
    'flex-layout',
    'Font Awesome',
    'GitHub Actions',
    'GitHub Pages',
    'Google',
    'Google Analytics',
    'Google Maps',
    'Google Pay',
    'GraphQL',
    'Hasura',
    'Ionic',
    'JSDoc',
    'Kendo UI',
    'Kubernetes',
    'MongoDB',
    'NestJS',
    '.Net',
    'NextJS',
    'NGXS',
    'NPM',
    'Nx',
    'OpenLayers',
    'Prettier',
    'PrimeNG',
    'Scully',
    'SingleSPA',
    'Storybook',
    'TailwindCSS',
    'TensorFlowJS',
    'VSCode',
    'Webstorm',
    'reCAPTCHA',
  ];
}
